# Test your FastAPI endpoints

GET http://127.0.0.1:8000/blog
Accept: application/json

###
GET http://127.0.0.1:8000/blog?limit=10&published=false
Accept: application/json


###
GET http://127.0.0.1:8000/blog/10
Accept: application/json

###
GET http://127.0.0.1:8000/blog/10/comments
Accept: application/json


###
GET http://127.0.0.1:8000/blog/unpublished
Accept: application/json